import globals from "globals"
import js from "@eslint/js"
import n from "eslint-plugin-n"
import stylistic from "@stylistic/eslint-plugin"

export default [
    js.configs.recommended,
    n.configs["flat/recommended"],
    {
        ignores: ["node_modules"],
        name: "root config",
        plugins: {
            "@stylistic": stylistic,
            "n": n,
        },
        languageOptions: {
            ecmaVersion: 2022,
            globals: {
                ...globals.nodeBuiltin,
                ...globals.es2022,
            },
        },
        rules: {
            "accessor-pairs": "error",
            "@stylistic/array-bracket-spacing": [
                "error",
                "never"
            ],
            "array-callback-return": "error",
            "arrow-body-style": "error",
            "@stylistic/arrow-parens": "error",
            "@stylistic/arrow-spacing": "error",
            "@stylistic/block-spacing": ["error", "always"],
            "@stylistic/brace-style": ["error", "1tbs"],
            "@stylistic/comma-dangle": ["error", "only-multiline"],
            "@stylistic/comma-spacing": ["error", {before: false, after: true}],
            "@stylistic/comma-style": ["error", "last"],
            "@stylistic/computed-property-spacing": ["error", "never"],
            "curly": ["error", "multi-line", "consistent"],
            "@stylistic/dot-location": ["error", "property"],
            "dot-notation": "error",
            "@stylistic/eol-last": "error",
            "eqeqeq": ["error", "always", {null: "ignore"}],
            "@stylistic/function-call-spacing": "error",
            "@stylistic/generator-star-spacing": "error",
            "n/handle-callback-err": "error",
            "id-match": ["error", "^_?(?:[A-Za-z$][\\w$]*|[$A-Z][$A-Z0-9]*(?:_[$A-Z0-9]+)*)$", {properties: false}],
            "@stylistic/indent": ["error", 4, {outerIIFEBody: 0, SwitchCase: 1}],
            "@stylistic/implicit-arrow-linebreak": ["error", "beside"],
            "@stylistic/key-spacing": "error",
            "@stylistic/keyword-spacing": "error",
            "@stylistic/linebreak-style": ["error", "unix"],
            "@stylistic/lines-around-comment": ["error", {
                beforeBlockComment: true,
                allowBlockStart: true,
                allowBlockEnd: true,
                allowObjectStart: true,
                allowObjectEnd: true,
                allowArrayStart: true,
                allowArrayEnd: true,
                allowClassStart: true,
                allowClassEnd: true,
            }],
            "@stylistic/multiline-comment-style": "off",
            "@stylistic/new-parens": "error",
            "@stylistic/newline-per-chained-call": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-bitwise": "error",
            "no-caller": "error",
            "@stylistic/no-confusing-arrow": "error",
            "no-div-regex": "error",
            "no-duplicate-imports": "error",
            "no-eval": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "@stylistic/no-extra-semi": "error",
            "@stylistic/no-floating-decimal": "error",
            "no-implicit-coercion": "error",
            "no-implicit-globals": "error",
            "no-implied-eval": "error",
            "no-iterator": "error",
            "no-lone-blocks": "error",
            "n/no-mixed-requires": "error",
            "@stylistic/no-multi-spaces": "error",
            "no-multi-str": "error",
            "@stylistic/no-multiple-empty-lines": "error",
            "no-native-reassign": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-object": "error",
            "n/no-new-require": "error",
            "no-new-wrappers": "error",
            "no-octal-escape": "error",
            "n/no-process-exit": "error",
            "no-proto": "error",
            "no-redeclare": "error",
            "no-restricted-syntax": [
                "error",
                {selector: "ForInStatement", message: "Use `for (const key of Object.keys(object))` instead."}
            ],
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-shadow": "error",
            "@stylistic/no-tabs": "error",
            "no-throw-literal": "error",
            "@stylistic/no-trailing-spaces": ["error", {skipBlankLines: true}],
            "no-undef-init": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unreachable-loop": "error",
            "no-unused-vars": ["error", {
                varsIgnorePattern: "^_",
                argsIgnorePattern: "^_",
                destructuredArrayIgnorePattern: "^_",
                reportUsedIgnorePattern: true,
            }],
            "no-useless-assignment": "error",
            "no-useless-call": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-var": "error",
            "@stylistic/no-whitespace-before-property": "error",
            "object-curly-spacing": ["error", "never"],
            "object-shorthand": "off",
            "one-var": ["error", {initialized: "never"}],
            "one-var-declaration-per-line": "off",
            "operator-assignment": ["error", "always"],
            "@stylistic/operator-linebreak": "off",
            "@stylistic/padded-blocks": ["error", "never"],
            "prefer-const": "error",
            "n/prefer-node-protocol": "error",
            "@stylistic/quotes": ["error", "double", {avoidEscape: true}],
            "radix": ["error", "always"],
            "require-yield": "error",
            "@stylistic/semi": ["error", "never"],
            "sort-imports": ["error", {allowSeparatedGroups: true}],
            "@stylistic/space-before-blocks": ["error", "always"],
            "@stylistic/space-before-function-paren": ["error", "never"],
            "@stylistic/space-in-parens": ["error", "never"],
            "@stylistic/space-unary-ops": "error",
            "strict": ["error", "global"],
            "@stylistic/template-curly-spacing": "error",
            "@stylistic/wrap-regex": "error",
            "@stylistic/yield-star-spacing": "error",
        }
    }
]
