on:
  repository_dispatch:
    types:
    - deploy
  workflow_dispatch:
    # Note: changes to this *must* be reflected in `lib/util.js`.
    inputs:
      repo:
        type: string
        required: true
      type:
        type: choice
        options:
        - npm
        - github-pages
        required: true
      packageName:
        type: string
        required: true
      tarballName:
        type: string
        required: true
      artifactId:
        type: number
        required: true
      workflowRunId:
        type: number
        required: true
      buildVersion:
        type: number
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci --production
    - uses: ./infra/internal/deploy
      with:
        npm_token: ${{ secrets.NPM_TOKEN }}
        gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }}
