name: Notify triage

on:
  workflow_call:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  id-token: write
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  notify:
    # Exclude dependabot's dependency updates. That's just going to annoy people.
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run workflow
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail

        echo "event name: $GITHUB_EVENT_NAME"

        case "$GITHUB_EVENT_NAME" in
          "issues") cmd=issue ;;
          "pull_request_target") cmd=pr ;;
          *)
            echo "::error::This action must only be run on 'issue' and 'pull_request_target' events"
            exit 1
            ;;
        esac

        id="$(jq -r .number <"$GITHUB_EVENT_PATH")"

        echo "cmd: $cmd"
        echo "id: $id"

        gh $cmd edit --repo "$GITHUB_REPOSITORY" "$id" --add-project 'Triage/bugs'
        gh $cmd comment --repo "$GITHUB_REPOSITORY" "$id" --body '@MithrilJS/triage Please take a look.'
