name: Notify triage

on:
  workflow_call:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Run workflow
      # Exclude dependabot's dependency updates. That's just going to annoy people.
      if: ${{ github.actor != 'dependabot[bot]' }}
      env:
        GH_TOKEN_SECRET: ${{ github.token }}
      run: |
        set -euo pipefail

        echo "event name: $GITHUB_EVENT_NAME"

        case "$GITHUB_EVENT_NAME" in
          "issue") cmd=issue ;;
          "pull_request_target") cmd=pr ;;
          *)
            echo "::error::This action must only be run on 'issue' and 'pull_request_target' events"
            exit 1
            ;;
        esac

        id="$(jq -r .number <"$GITHUB_EVENT_PATH")"

        echo "cmd: $cmd"
        echo "id: $id"

        export GITHUB_TOKEN="$GH_TOKEN_SECRET"
        gh $cmd edit --repo "$GITHUB_REPOSITORY" "$id" --add-project 'Triage/bugs'
        gh $cmd comment --repo "$GITHUB_REPOSITORY" "$id" --body '@MithrilJS/triage Please take a look.'
