name: Reject PR

on:
  workflow_call:
    inputs:
      correct_branch:
        type: string
        default: main
    secrets:
      ISSUE_PR_PROJECTS_TOKEN:
        required: true

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -euo pipefail
        echo "event name: $GITHUB_EVENT_NAME"
        if [[ "$GITHUB_EVENT_NAME" != "pull_request_target" ]]; then
          echo "::error::This action must only be run on 'pull_request_target' events"
          exit 1
        fi
        gh pr close --repo "$GITHUB_REPOSITORY" "$PR_NUMBER" --comment "$MESSAGE" --reason 'not planned' &&
        gh pr lock --repo "$GITHUB_REPOSITORY" "$PR_NUMBER" --reason 'resolved'
      env:
        GH_TOKEN: ${{ secrets.ISSUE_PR_PROJECTS_TOKEN }}
        PR_NUMBER: ${{ github.event.number }}
        MESSAGE: Hey @${{ github.actor }}, this pull request should be directed towards `${{ inputs.correct_branch }}`. Please file a new pull request targeting that branch instead.
