on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: git clone --depth=1 "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" .
    - run: npm ci
    - run: npx eslint .
    - run: npm test
