on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
  push:
    branches: [main]
permissions:
  actions: write
  contents: read
jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
