on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main

jobs:
  test_config:
    runs-on:
    - ubuntu-latest
    - windows-latest
    steps:
    - run: git clone --depth=1 "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git" .
    - run: npm ci
    - run: npx eslint .
    - run: node ./lib/config.js
